//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Folluk.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFollukEntities : DbContext
    {
        public dbFollukEntities()
            : base("name=dbFollukEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAccount> tblAccounts { get; set; }
        public virtual DbSet<tblAccountCredential> tblAccountCredentials { get; set; }
        public virtual DbSet<tblAnimal> tblAnimals { get; set; }
        public virtual DbSet<tblAnimalType> tblAnimalTypes { get; set; }
        public virtual DbSet<tblArticle> tblArticles { get; set; }
        public virtual DbSet<tblCity> tblCities { get; set; }
        public virtual DbSet<tblConversation> tblConversations { get; set; }
        public virtual DbSet<tblConversationReply> tblConversationReplies { get; set; }
        public virtual DbSet<tblCoop> tblCoops { get; set; }
        public virtual DbSet<tblCoopAnimal> tblCoopAnimals { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblDistrict> tblDistricts { get; set; }
        public virtual DbSet<tblFarm> tblFarms { get; set; }
        public virtual DbSet<tblMedicine> tblMedicines { get; set; }
        public virtual DbSet<tblMedicineAnimal> tblMedicineAnimals { get; set; }
        public virtual DbSet<tblNest> tblNests { get; set; }
    }
}
