//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Folluk.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAccount()
        {
            this.tblAccountCredentials = new HashSet<tblAccountCredential>();
            this.tblArticles = new HashSet<tblArticle>();
            this.tblConversations = new HashSet<tblConversation>();
            this.tblConversationReplies = new HashSet<tblConversationReply>();
            this.tblFarms = new HashSet<tblFarm>();
        }
    
        public int AccountId { get; set; }
        public string Fullname { get; set; }
        public string Gsm1 { get; set; }
        public string Gsm2 { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string FacebookAccount { get; set; }
        public string ProfilePicture { get; set; }
    
        public virtual tblDistrict tblDistrict { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountCredential> tblAccountCredentials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblArticle> tblArticles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConversation> tblConversations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConversationReply> tblConversationReplies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFarm> tblFarms { get; set; }
    }
}
