//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Folluk.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNest
    {
        public int NestId { get; set; }
        public Nullable<int> FarmId { get; set; }
        public Nullable<int> CoopId { get; set; }
        public Nullable<int> AnimalId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> DeployDate { get; set; }
        public Nullable<int> StartQuantity { get; set; }
        public Nullable<int> ResultQuantity { get; set; }
        public string ResultRate { get; set; }
        public string Notes { get; set; }
    
        public virtual tblAnimal tblAnimal { get; set; }
        public virtual tblCoop tblCoop { get; set; }
        public virtual tblFarm tblFarm { get; set; }
    }
}
